require("config.options")
require("config.keymaps")
require("config.session")
require("config.tabline")
require("config.diagnostics")
require("config.autocmds")
require("config.marks")
require("config.lsp")
require("config.packui")
-- require("config.ui2") -- conflicts with noice.nvim
