# Change bind-key
#set -g default-terminal "xterm-kitty"
#set-option -sa terminal-overrides ",xterm*:Tc,wezterm:Tc"
#set -g default-terminal "xterm-kitty"
set -g default-terminal "${TERM}"
if 'infocmp -x tmux-256color > /dev/null 2>&1' 'set -g default-terminal "tmux-256color"'
set -g default-shell /opt/homebrew/bin/fish
set -g default-command /opt/homebrew/bin/fish

set -g mode-keys vi
set -g mouse on

unbind C-b
set -g prefix C-s
bind C-s send-prefix

# Vim style pane selection
bind h select-pane -L
bind j select-pane -D
bind k select-pane -U
bind l select-pane -R

# Start windows and panes at 1, not 0
set -g base-index 1
set -g pane-base-index 1
set-window-option -g pane-base-index 1
set-option -g renumber-windows on

setw -g automatic-rename on   # rename window to reflect current program
set -g renumber-windows on    # renumber windows when a window is closed

set -g set-titles on          # set terminal title

# Some configs

setw -g xterm-keys on
set -g escape-time 10             # zero-out escape time delay
set -g history-limit 1000000     # increase history size (from 2,000)
set -g renumber-windows on       # renumber all windows when any window is closed
set -g set-clipboard on          # use system clipboard
set -g allow-passthrough on      # allow image protocols (kitty graphics)

# Use Alt-arrow keys without prefix key to switch panes
bind -n M-Left resize-pane -L 1
bind -n M-Down resize-pane -D 1
bind -n M-Up resize-pane -U 1
bind -n M-Right resize-pane -R 1

# Shift arrow to switch windows
bind -n S-Left  previous-window
bind -n S-Right next-window

# Shift Alt vim keys to switch windows
bind -n M-H previous-window
bind -n M-L next-window

# Display Popups
bind i display-popup -E "fish"
bind S-Z display-popup \
  -d "#{pane_current_path}" \
  -w 75% \
  -h 75% \
  -E "fish"

# Display Menu
bind d display-menu -T "#[align=centre]Dotfiles" -x C -y C \
  ".fish"             f  "display-popup -E 'nvim ~/.config/fish/config.fish'" \
  ".zshrc"            z  "display-popup -E 'nvim ~/.config/zsh/.zshrc'" \
  ".tmux.conf"        t  "display-popup -E 'nvim ~/.config/tmux/tmux.conf'" \
  ".config/nvim"      n  "display-popup -E 'nvim ~/.config/nvim/init.lua'" \
  "Exit"              q  ""

set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'tmux-plugins/tmux-sensible'
set -g @plugin 'tmux-plugins/tmux-yank'
set -g @plugin 'christoomey/vim-tmux-navigator'
set -g @plugin 'tmux-plugins/tmux-resurrect'
set -g @plugin 'omerxx/catppuccin-tmux'
set -g @plugin 'fcsonline/tmux-thumbs'
set -g @plugin 'jimeh/tmuxifier'
set -g @catppuccin_flavour 'macchiato'

run '~/.config/tmux/plugins/tpm/tpm'

# set vi-mode
setw -g mode-keys vi

set -g @thumbs-command 'echo -n {} | wl-copy'
set -g @thumbs-upcase-command 'echo -n {} | wl-paste'
set -g status-position top

# keybindings
bind-key -T copy-mode-vi v send-keys -X begin-selection
bind-key -T copy-mode-vi C-v send-keys -X rectangle-toggle
bind-key -T copy-mode-vi y send-keys -X copy-selection-and-cancel

bind '"' split-window -v -c "#{pane_current_path}"
bind % split-window -h -c "#{pane_current_path}"

bind r source-file ~/.config/tmux/tmux.conf
